package system

import (
	"errors"
	"sync"
)

const (
	ByteResType = iota
	StringResType
)

type codetype interface{}

type Generator struct {
	mu       sync.RWMutex
	code     map[string][]codetype
	Pipeline []string
	res_type int
}

func (g *Generator) addToCode(code codetype, point string) {
	g.mu.Lock()
	defer g.mu.Unlock()
	if _, ok := g.code[point]; !ok {
		g.code[point] = []codetype{}
	}
	g.code[point] = append(g.code[point], code)
}

func (g *Generator) AddStrings(code []string, point string) error {
	if g.res_type != StringResType {
		return errors.New("Invalid operation: can't add strings to bytes")
	}
	g.addToCode(code, point)
	return nil
}

func (g *Generator) AddString(code string, point string) error {
	if g.res_type != StringResType {
		return errors.New("Invalid operation: can't add strings to bytes")
	}
	g.addToCode([]string{code}, point)
	return nil
}

func (g *Generator) AddBytes(code []byte, point string) error {
	if g.res_type != ByteResType {
		return errors.New("Invalid operation: can't add bytes to strings")
	}
	g.addToCode(code, point)
	return nil
}

func (g *Generator) GetBytesRes() ([]byte, error) {
	g.mu.RLock()
	defer g.mu.RUnlock()
	if g.res_type != ByteResType {
		return nil, errors.New("Generation failed. Can't get bytes from generated string code")
	}
	res := []byte{}
	for _, point := range g.Pipeline {
		point_code, ok := g.code[point]
		if !ok {
			return nil, errors.New("Generation failed. Can't find '" + point + "' pipeline point")
		}
		for _, code := range point_code {
			if bytes, ok := code.([]byte); ok {
				res = append(res, bytes...)
			}
		}
	}
	return res, nil
}

func (g *Generator) GetStringArrRes() ([]string, error) {
	g.mu.RLock()
	defer g.mu.RUnlock()
	if g.res_type != StringResType {
		return nil, errors.New("Generation failed. Can't get string from generated bytes")
	}
	res := []string{}
	for _, point := range g.Pipeline {
		point_code, ok := g.code[point]
		if !ok {
			return nil, errors.New("Generation failed. Can't find '" + point + "' pipeline point")
		}
		for _, code := range point_code {
			if str, ok := code.([]string); ok {
				res = append(res, str...)
			} else {
				return nil, errors.New("unexpected type in Generator")
			}
		}
	}
	return res, nil
}

func (g *Generator) GetStringRes(sep string) (string, error) {
	res := ""
	arr, err := g.GetStringArrRes()
	if err != nil {
		return "", err
	}
	for idx, val := range arr {
		res += val
		if idx != (len(arr) - 1) {
			res += sep
		}
	}
	return res, nil
}

func NewGenerator(res_type int, pipeline []string) *Generator {
	return &Generator{
		code:     map[string][]codetype{},
		Pipeline: pipeline,
		res_type: res_type,
	}
}
